name: textlint on pr

on:
  pull_request:
    branches: [master]

jobs:
  text-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-target-repo
        uses: actions/checkout@v2

      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          textlint_flags: "blogs/**"
