name: textlint

on:
  push:
    branches: [cicd_sample]

jobs:
  text-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-target-repo
        uses: actions/checkout@v2

      - name: set-up-node
        uses: actions/setup-node@v2

      - name: install textlint
        run: "npm install --save-dev textlint"

      - name: install textlint rule
        run: "npm install --save-dev textlint-rule-no-todo textlint-rule-preset-ja-technical-writing textlint-rule-preset-ja-spacing"

      - name: execute textlint
        run: "npx textlint blogs/*"
